[[manager.prepend_keymap]]
on   = [ "t" ]
run  = "plugin --sync max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on   = [ "<C-c>" ]
run  = '''
shell --confirm
'cat "$0" | kitten clipboard'
'''
desc = "copy the file content to clipboard"

[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run  = "close"
desc = "Cancel input"


[[manager.prepend_keymap]]
on   = [ "<C-Backspace>" ]
run = "remove --force --permanently"
desc = "Permanently delete the files"

[[manager.prepend_keymap]]
on   = [ "<C-o>" ]
run = "tab_create"
desc = "Permanently delete the files"

[[manager.prepend_keymap]]
on   = [ "<C-s>" ]
run  = '''
shell  --block --confirm
'kitten transfer -p badlook "$@" /Users/look/Downloads/ ||  
kitten transfer -p badlook "$0" /Users/look/Downloads/'
'''
desc = "Download selected files using Kitty transfer"



